# Generated by Django 6.0.3 on 2026-06-10 02:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reversewebsearch', '0006_alter_websearchresults_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verdict', models.CharField(choices=[('real', 'Real News'), ('fake', 'Fake News'), ('suspicious', 'Suspicious'), ('unconfirmed', 'Unconfirmed')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='0.0 (lowest) to 1.0 (highest confidence)')),
                ('short_summary', models.CharField(blank=True, default='', help_text='One-sentence summary of the verdict', max_length=300)),
                ('explanation', models.TextField(help_text='Detailed reasoning from the LLM')),
                ('key_evidence', models.JSONField(blank=True, default=list, help_text='List of key evidence items')),
                ('llm_raw_response', models.JSONField(blank=True, default=dict, null=True)),
                ('llm_prompt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('websearch_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='robot_analysis', to='reversewebsearch.websearchresults')),
            ],
            options={
                'verbose_name_plural': 'Robot Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
