# Generated by Django 6.0.3 on 2026-06-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotanalysis',
            name='research_queries',
            field=models.JSONField(blank=True, default=list, help_text='List of SearXNG search queries generated for this analysis'),
        ),
        migrations.AddField(
            model_name='robotanalysis',
            name='research_report',
            field=models.JSONField(blank=True, default=dict, help_text='Research report with summary, sources, images, and videos from SearXNG'),
        ),
    ]
