# Generated by Django 6.0.3 on 2026-05-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversewebsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websearchresults',
            name='image',
            field=models.ImageField(default=None, upload_to='../reversewebsearch/'),
            preserve_default=False,
        ),
    ]
