# Generated by Django 6.0.3 on 2026-05-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversewebsearch', '0002_websearchresults_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websearchresults',
            name='image',
            field=models.ImageField(upload_to='reversewebsearch/'),
        ),
    ]
