# Generated by Django 6.0.3 on 2026-05-30 21:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reversewebsearch', '0003_alter_websearchresults_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websearchresults',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
