# Generated by Django 6.0.3 on 2026-06-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversewebsearch', '0004_alter_websearchresults_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websearchresults',
            name='alias',
            field=models.CharField(default='Reverse find <function random_int at 0x7cfeeddb6480>', max_length=255),
        ),
    ]
