# Generated by Django 6.0.3 on 2026-06-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversewebsearch', '0005_websearchresults_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websearchresults',
            name='alias',
            field=models.CharField(default='Reverse find <function random_int at 0x70e2561ee480>', max_length=255),
        ),
    ]
