# Generated by Django 6.0.3 on 2026-06-15 15:57

import reversewebsearch.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversewebsearch', '0006_alter_websearchresults_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='websearchresults',
            name='alias',
            field=models.CharField(default=reversewebsearch.models.default_alias, max_length=255),
        ),
        migrations.AlterField(
            model_name='websearchresults',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='websearchresults',
            index=models.Index(fields=['user', '-created_at'], name='idx_user_created_at'),
        ),
        migrations.AddIndex(
            model_name='websearchresults',
            index=models.Index(fields=['query'], name='idx_query'),
        ),
    ]
